version: "3.8"

services:
  web:
    image: "${DHIS2_IMAGE:-dhis2/core-dev:local}"
    restart: "always"
    user: "1000:1000"
    ports:
      - 8080:8080 # DHIS2
      - 8081:8081 # Debugger: connect using commandline flag -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
      - 9010:9010 # JMX port (for example for VisualVM)
    volumes:
      - ./docker/dhis.conf:${DHIS2_HOME:-/DHIS2_home}/dhis.conf:ro
      - ./docker/log4j2.xml:${DHIS2_HOME:-/DHIS2_home}/log4j2.xml:ro
      #- /mnt/disks/disk1/dhis2:${DHIS2_HOME:-/DHIS2_home}:rw
      - dhis2_data:${DHIS2_HOME:-/DHIS2_home}:rw
    environment:
      DHIS2_HOME: ${DHIS2_HOME:-/DHIS2_home}
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081 \
              -Dlog4j2.configurationFile=${DHIS2_HOME:-/DHIS2_home}/log4j2.xml
              -Dcom.sun.management.jmxremote \
              -Dcom.sun.management.jmxremote.port=9010 \
              -Dcom.sun.management.jmxremote.local.only=false \
              -Dcom.sun.management.jmxremote.authenticate=false \
              -Dcom.sun.management.jmxremote.ssl=false \
              -Ddhis2.home=${DHIS2_HOME:-/DHIS2_home}"
    #command: sh -c "sudo chown 1000:1000 /opt/dhis2"
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.csrf.headers.customRequestHeaders.X-CSRF-Token=71eac59bbe12ce53f3dd1b6d7228fe4daa3016b388963fb84d371eed5ba78d18
      - traefik.http.middlewares.cookies.headers.customResponseHeaders.Set-Cookie=sameSite=Strict
      - traefik.http.routers.dhis-web.middlewares=redirect-web-secure
      - traefik.http.routers.dhis-web.rule=Host(`hmis.doh.gov.ph`)
      - traefik.http.routers.dhis-web.entrypoints=web
      - traefik.http.routers.dhis-web-secure.rule=Host(`hmis.doh.gov.ph`)
      - traefik.http.routers.dhis-web-secure.entrypoints=web-secure
      - traefik.http.routers.dhis-web-secure.tls=true
      - traefik.http.routers.dhis-web-secure.tls.certresolver=default
      - traefik.http.routers.dhis-web-secure.middlewares=csrf
      - traefik.http.routers.dhis-web-secure.middlewares=cookies
      - traefik.http.routers.dhis-web-secure.middlewares=https-redirect
      - traefik.http.routers.dhis-web-secure.service=dhis-service
      - traefik.http.services.dhis-service.loadbalancer.server.port=8080
    networks:
      - web
networks:
  web:
    external: true

volumes:
  dhis2_data: 
    driver_opts:
      type: cifs
      o: username=srtakada@DOH,password=S31g1RT4k4d4,uid=1000,gid=1000,dir_mode=0775,vers=3.1.1
      device: //10.11.132.178/ssed2/disks/applications/dhis2